### ISSUE TITLE
Updating an existing domain with new ip

### ISSUE THREAD

**Issue by stephencroberts** [mattes/vagrant-dnsmasq#16]
If you change the IP address of a vm that's already been provisioned, the plugin says that it updated the ip address, but the entry in dnsmasq.conf doesn't change, so the domain no longer resolves. 

**Steps to reproduce:**
- `vagrant up`
- Change the IP in Vagrantfile
- `vagrant halt` and `vagrant up`

The VM is no longer accessible with the dnsmasq domain

**Comment by mattes** [comment]
great! thanks for the fix!
